# Generated by Django 3.2.25 on 2025-08-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='宠物小猫', max_length=100)),
                ('happiness', models.IntegerField(default=8)),
                ('health', models.IntegerField(default=8)),
                ('hunger', models.IntegerField(default=0)),
                ('growth', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('time_cycle', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
