# Generated by Django 3.2.25 on 2025-08-07 03:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('virtualpet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualpet',
            name='last_doctor_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='virtualpet',
            name='last_feed_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='virtualpet',
            name='last_play_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='virtualpet',
            name='last_walk_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
